
// Full Messier Catalog
export const messier = [
    { id: 'M1', ngc: 'NGC 1952', const: 'Tau', type: 'SNR', mag: 8.4, size: '6x4', name: 'Rák-köd', desc: 'Szupernóva-maradvány' },
    { id: 'M2', ngc: 'NGC 7089', const: 'Aqr', type: 'GC', mag: 6.5, size: '16', name: '', desc: 'Gömbhalmaz' },
    { id: 'M3', ngc: 'NGC 5272', const: 'CVn', type: 'GC', mag: 6.2, size: '18', name: '', desc: 'Gömbhalmaz' },
    { id: 'M4', ngc: 'NGC 6121', const: 'Sco', type: 'GC', mag: 5.6, size: '26', name: '', desc: 'Gömbhalmaz' },
    { id: 'M5', ngc: 'NGC 5904', const: 'Ser', type: 'GC', mag: 5.6, size: '17', name: '', desc: 'Gömbhalmaz' },
    { id: 'M6', ngc: 'NGC 6405', const: 'Sco', type: 'OC', mag: 4.2, size: '25', name: 'Pillangó-halmaz', desc: 'Nyílthalmaz' },
    { id: 'M7', ngc: 'NGC 6475', const: 'Sco', type: 'OC', mag: 3.3, size: '80', name: 'Ptolemaiosz halmaza', desc: 'Nyílthalmaz' },
    { id: 'M8', ngc: 'NGC 6523', const: 'Sgr', type: 'NB', mag: 6.0, size: '90x40', name: 'Lagúna-köd', desc: 'Emissziós köd' },
    { id: 'M9', ngc: 'NGC 6333', const: 'Oph', type: 'GC', mag: 7.7, size: '12', name: '', desc: 'Gömbhalmaz' },
    { id: 'M10', ngc: 'NGC 6254', const: 'Oph', type: 'GC', mag: 6.6, size: '20', name: '', desc: 'Gömbhalmaz' },
    { id: 'M11', ngc: 'NGC 6705', const: 'Sct', type: 'OC', mag: 5.8, size: '14', name: 'Vadkacsa-halmaz', desc: 'Nyílthalmaz' },
    { id: 'M12', ngc: 'NGC 6218', const: 'Oph', type: 'GC', mag: 6.7, size: '16', name: '', desc: 'Gömbhalmaz' },
    { id: 'M13', ngc: 'NGC 6205', const: 'Her', type: 'GC', mag: 5.8, size: '20', name: 'Herkules-halmaz', desc: 'Nagy gömbhalmaz' },
    { id: 'M14', ngc: 'NGC 6402', const: 'Oph', type: 'GC', mag: 7.6, size: '11', name: '', desc: 'Gömbhalmaz' },
    { id: 'M15', ngc: 'NGC 7078', const: 'Peg', type: 'GC', mag: 6.2, size: '18', name: '', desc: 'Gömbhalmaz' },
    { id: 'M16', ngc: 'NGC 6611', const: 'Ser', type: 'NB', mag: 6.4, size: '7', name: 'Sas-köd', desc: 'Nyílthalmaz és köd' },
    { id: 'M17', ngc: 'NGC 6618', const: 'Sgr', type: 'NB', mag: 6.0, size: '11', name: 'Omega-köd', desc: 'Emissziós köd' },
    { id: 'M18', ngc: 'NGC 6613', const: 'Sgr', type: 'OC', mag: 7.5, size: '9', name: '', desc: 'Nyílthalmaz' },
    { id: 'M19', ngc: 'NGC 6273', const: 'Oph', type: 'GC', mag: 6.8, size: '17', name: '', desc: 'Gömbhalmaz' },
    { id: 'M20', ngc: 'NGC 6514', const: 'Sgr', type: 'NB', mag: 6.3, size: '28', name: 'Trifid-köd', desc: 'Reflexiós/Emissziós köd' },
    { id: 'M21', ngc: 'NGC 6531', const: 'Sgr', type: 'OC', mag: 6.5, size: '13', name: '', desc: 'Nyílthalmaz' },
    { id: 'M22', ngc: 'NGC 6656', const: 'Sgr', type: 'GC', mag: 5.1, size: '32', name: '', desc: 'Gömbhalmaz' },
    { id: 'M23', ngc: 'NGC 6494', const: 'Sgr', type: 'OC', mag: 5.5, size: '27', name: '', desc: 'Nyílthalmaz' },
    { id: 'M24', ngc: 'IC 4715', const: 'Sgr', type: 'OC', mag: 4.6, size: '90', name: 'Kis Sagittarius-csillagfelhő', desc: 'Tejút-folt' },
    { id: 'M25', ngc: 'IC 4725', const: 'Sgr', type: 'OC', mag: 4.6, size: '32', name: '', desc: 'Nyílthalmaz' },
    { id: 'M26', ngc: 'NGC 6694', const: 'Sct', type: 'OC', mag: 8.0, size: '15', name: '', desc: 'Nyílthalmaz' },
    { id: 'M27', ngc: 'NGC 6853', const: 'Vul', type: 'PN', mag: 7.4, size: '8x6', name: 'Súlyzó-köd', desc: 'Planetáris köd' },
    { id: 'M28', ngc: 'NGC 6626', const: 'Sgr', type: 'GC', mag: 6.8, size: '11', name: '', desc: 'Gömbhalmaz' },
    { id: 'M29', ngc: 'NGC 6913', const: 'Cyg', type: 'OC', mag: 7.1, size: '7', name: '', desc: 'Nyílthalmaz' },
    { id: 'M30', ngc: 'NGC 7099', const: 'Cap', type: 'GC', mag: 7.2, size: '12', name: '', desc: 'Gömbhalmaz' },
    { id: 'M31', ngc: 'NGC 224', const: 'And', type: 'GAL', mag: 3.4, size: '178x63', name: 'Androméda-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M32', ngc: 'NGC 221', const: 'And', type: 'GAL', mag: 8.1, size: '8x6', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M33', ngc: 'NGC 598', const: 'Tri', type: 'GAL', mag: 5.7, size: '71x42', name: 'Triangulum-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M34', ngc: 'NGC 1039', const: 'Per', type: 'OC', mag: 5.5, size: '35', name: '', desc: 'Nyílthalmaz' },
    { id: 'M35', ngc: 'NGC 2168', const: 'Gem', type: 'OC', mag: 5.3, size: '28', name: '', desc: 'Nyílthalmaz' },
    { id: 'M36', ngc: 'NGC 1960', const: 'Aur', type: 'OC', mag: 6.3, size: '12', name: '', desc: 'Nyílthalmaz' },
    { id: 'M37', ngc: 'NGC 2099', const: 'Aur', type: 'OC', mag: 6.2, size: '24', name: '', desc: 'Nyílthalmaz' },
    { id: 'M38', ngc: 'NGC 1912', const: 'Aur', type: 'OC', mag: 7.4, size: '21', name: '', desc: 'Nyílthalmaz' },
    { id: 'M39', ngc: 'NGC 7092', const: 'Cyg', type: 'OC', mag: 4.6, size: '32', name: '', desc: 'Nyílthalmaz' },
    { id: 'M40', ngc: '-', const: 'UMa', type: 'DS', mag: 8.4, size: '0.8', name: 'Winnecke 4', desc: 'Kettőscsillag' },
    { id: 'M41', ngc: 'NGC 2287', const: 'CMa', type: 'OC', mag: 4.5, size: '38', name: '', desc: 'Nyílthalmaz' },
    { id: 'M42', ngc: 'NGC 1976', const: 'Ori', type: 'NB', mag: 4.0, size: '85x60', name: 'Orion-köd', desc: 'Emissziós köd' },
    { id: 'M43', ngc: 'NGC 1982', const: 'Ori', type: 'NB', mag: 9.0, size: '20x15', name: 'De Mairan-köd', desc: 'Emissziós köd' },
    { id: 'M44', ngc: 'NGC 2632', const: 'Cnc', type: 'OC', mag: 3.7, size: '95', name: 'Jászol-halmaz', desc: 'Nyílthalmaz (Praesepe)' },
    { id: 'M45', ngc: '-', const: 'Tau', type: 'OC', mag: 1.6, size: '110', name: 'Fiastyúk', desc: 'Nyílthalmaz (Pleiades)' },
    { id: 'M46', ngc: 'NGC 2437', const: 'Pup', type: 'OC', mag: 6.0, size: '27', name: '', desc: 'Nyílthalmaz' },
    { id: 'M47', ngc: 'NGC 2422', const: 'Pup', type: 'OC', mag: 5.2, size: '30', name: '', desc: 'Nyílthalmaz' },
    { id: 'M48', ngc: 'NGC 2548', const: 'Hya', type: 'OC', mag: 5.5, size: '54', name: '', desc: 'Nyílthalmaz' },
    { id: 'M49', ngc: 'NGC 4472', const: 'Vir', type: 'GAL', mag: 8.4, size: '10x8', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M50', ngc: 'NGC 2323', const: 'Mon', type: 'OC', mag: 5.9, size: '16', name: '', desc: 'Nyílthalmaz' },
    { id: 'M51', ngc: 'NGC 5194', const: 'CVn', type: 'GAL', mag: 8.4, size: '11x7', name: 'Örvény-köd', desc: 'Spirálgalaxis' },
    { id: 'M52', ngc: 'NGC 7654', const: 'Cas', type: 'OC', mag: 7.3, size: '13', name: '', desc: 'Nyílthalmaz' },
    { id: 'M53', ngc: 'NGC 5024', const: 'Com', type: 'GC', mag: 7.6, size: '13', name: '', desc: 'Gömbhalmaz' },
    { id: 'M54', ngc: 'NGC 6715', const: 'Sgr', type: 'GC', mag: 7.6, size: '12', name: '', desc: 'Gömbhalmaz' },
    { id: 'M55', ngc: 'NGC 6809', const: 'Sgr', type: 'GC', mag: 6.3, size: '19', name: '', desc: 'Gömbhalmaz' },
    { id: 'M56', ngc: 'NGC 6779', const: 'Lyr', type: 'GC', mag: 8.3, size: '9', name: '', desc: 'Gömbhalmaz' },
    { id: 'M57', ngc: 'NGC 6720', const: 'Lyr', type: 'PN', mag: 8.8, size: '1.4x1', name: 'Gyűrűs-köd', desc: 'Planetáris köd' },
    { id: 'M58', ngc: 'NGC 4579', const: 'Vir', type: 'GAL', mag: 9.7, size: '6x5', name: '', desc: 'Spirálgalaxis' },
    { id: 'M59', ngc: 'NGC 4621', const: 'Vir', type: 'GAL', mag: 9.6, size: '5x4', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M60', ngc: 'NGC 4649', const: 'Vir', type: 'GAL', mag: 8.8, size: '7x6', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M61', ngc: 'NGC 4303', const: 'Vir', type: 'GAL', mag: 9.7, size: '6x6', name: '', desc: 'Spirálgalaxis' },
    { id: 'M62', ngc: 'NGC 6266', const: 'Oph', type: 'GC', mag: 6.5, size: '15', name: '', desc: 'Gömbhalmaz' },
    { id: 'M63', ngc: 'NGC 5055', const: 'CVn', type: 'GAL', mag: 8.6, size: '12x8', name: 'Napraforgó-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M64', ngc: 'NGC 4826', const: 'Com', type: 'GAL', mag: 8.5, size: '10x5', name: 'Feketeszem-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M65', ngc: 'NGC 3623', const: 'Leo', type: 'GAL', mag: 9.3, size: '10x3', name: '', desc: 'Spirálgalaxis (Leo Triplet)' },
    { id: 'M66', ngc: 'NGC 3627', const: 'Leo', type: 'GAL', mag: 8.9, size: '9x4', name: '', desc: 'Spirálgalaxis (Leo Triplet)' },
    { id: 'M67', ngc: 'NGC 2682', const: 'Cnc', type: 'OC', mag: 6.1, size: '30', name: '', desc: 'Nyílthalmaz' },
    { id: 'M68', ngc: 'NGC 4590', const: 'Hya', type: 'GC', mag: 7.8, size: '11', name: '', desc: 'Gömbhalmaz' },
    { id: 'M69', ngc: 'NGC 6637', const: 'Sgr', type: 'GC', mag: 7.6, size: '10', name: '', desc: 'Gömbhalmaz' },
    { id: 'M70', ngc: 'NGC 6681', const: 'Sgr', type: 'GC', mag: 7.9, size: '8', name: '', desc: 'Gömbhalmaz' },
    { id: 'M71', ngc: 'NGC 6838', const: 'Sge', type: 'GC', mag: 8.2, size: '7', name: '', desc: 'Gömbhalmaz' },
    { id: 'M72', ngc: 'NGC 6981', const: 'Aqr', type: 'GC', mag: 9.3, size: '7', name: '', desc: 'Gömbhalmaz' },
    { id: 'M73', ngc: 'NGC 6994', const: 'Aqr', type: 'OC', mag: 9.0, size: '3', name: '', desc: 'Aszterizmus' },
    { id: 'M74', ngc: 'NGC 628', const: 'Psc', type: 'GAL', mag: 9.4, size: '10x10', name: '', desc: 'Spirálgalaxis' },
    { id: 'M75', ngc: 'NGC 6864', const: 'Sgr', type: 'GC', mag: 8.5, size: '7', name: '', desc: 'Gömbhalmaz' },
    { id: 'M76', ngc: 'NGC 650', const: 'Per', type: 'PN', mag: 10.1, size: '3x2', name: 'Kis Súlyzó-köd', desc: 'Planetáris köd' },
    { id: 'M77', ngc: 'NGC 1068', const: 'Cet', type: 'GAL', mag: 8.9, size: '7x6', name: '', desc: 'Spirálgalaxis' },
    { id: 'M78', ngc: 'NGC 2068', const: 'Ori', type: 'NB', mag: 8.3, size: '8x6', name: '', desc: 'Reflexiós köd' },
    { id: 'M79', ngc: 'NGC 1904', const: 'Lep', type: 'GC', mag: 7.7, size: '9', name: '', desc: 'Gömbhalmaz' },
    { id: 'M80', ngc: 'NGC 6093', const: 'Sco', type: 'GC', mag: 7.3, size: '10', name: '', desc: 'Gömbhalmaz' },
    { id: 'M81', ngc: 'NGC 3031', const: 'UMa', type: 'GAL', mag: 6.9, size: '21x10', name: 'Bode-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M82', ngc: 'NGC 3034', const: 'UMa', type: 'GAL', mag: 8.4, size: '9x4', name: 'Szivar-galaxis', desc: 'Starburst galaxis' },
    { id: 'M83', ngc: 'NGC 5236', const: 'Hya', type: 'GAL', mag: 7.6, size: '13x11', name: 'Déli Szélkerék', desc: 'Spirálgalaxis' },
    { id: 'M84', ngc: 'NGC 4374', const: 'Vir', type: 'GAL', mag: 9.1, size: '6x6', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M85', ngc: 'NGC 4382', const: 'Com', type: 'GAL', mag: 9.1, size: '7x5', name: '', desc: 'Lencse alakú galaxis' },
    { id: 'M86', ngc: 'NGC 4406', const: 'Vir', type: 'GAL', mag: 8.9, size: '9x6', name: '', desc: 'Lencse alakú galaxis' },
    { id: 'M87', ngc: 'NGC 4486', const: 'Vir', type: 'GAL', mag: 8.6, size: '8x7', name: 'Virgo A', desc: 'Elliptikus galaxis' },
    { id: 'M88', ngc: 'NGC 4501', const: 'Com', type: 'GAL', mag: 9.6, size: '7x4', name: '', desc: 'Spirálgalaxis' },
    { id: 'M89', ngc: 'NGC 4552', const: 'Vir', type: 'GAL', mag: 9.8, size: '5x5', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M90', ngc: 'NGC 4569', const: 'Vir', type: 'GAL', mag: 9.5, size: '10x4', name: '', desc: 'Spirálgalaxis' },
    { id: 'M91', ngc: 'NGC 4548', const: 'Com', type: 'GAL', mag: 10.2, size: '5x4', name: '', desc: 'Spirálgalaxis' },
    { id: 'M92', ngc: 'NGC 6341', const: 'Her', type: 'GC', mag: 6.4, size: '14', name: '', desc: 'Gömbhalmaz' },
    { id: 'M93', ngc: 'NGC 2447', const: 'Pup', type: 'OC', mag: 6.0, size: '22', name: '', desc: 'Nyílthalmaz' },
    { id: 'M94', ngc: 'NGC 4736', const: 'CVn', type: 'GAL', mag: 8.2, size: '11x9', name: '', desc: 'Spirálgalaxis' },
    { id: 'M95', ngc: 'NGC 3351', const: 'Leo', type: 'GAL', mag: 9.7, size: '7x5', name: '', desc: 'Spirálgalaxis' },
    { id: 'M96', ngc: 'NGC 3368', const: 'Leo', type: 'GAL', mag: 9.2, size: '8x5', name: '', desc: 'Spirálgalaxis' },
    { id: 'M97', ngc: 'NGC 3587', const: 'UMa', type: 'PN', mag: 9.9, size: '3', name: 'Bagoly-köd', desc: 'Planetáris köd' },
    { id: 'M98', ngc: 'NGC 4192', const: 'Com', type: 'GAL', mag: 10.1, size: '10x3', name: '', desc: 'Spirálgalaxis' },
    { id: 'M99', ngc: 'NGC 4254', const: 'Com', type: 'GAL', mag: 9.9, size: '5x5', name: '', desc: 'Spirálgalaxis' },
    { id: 'M100', ngc: 'NGC 4321', const: 'Com', type: 'GAL', mag: 9.3, size: '7x6', name: '', desc: 'Spirálgalaxis' },
    { id: 'M101', ngc: 'NGC 5457', const: 'UMa', type: 'GAL', mag: 7.9, size: '29x27', name: 'Szélkerék-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M102', ngc: 'NGC 5866', const: 'Dra', type: 'GAL', mag: 9.9, size: '5x2', name: 'Orsó-galaxis', desc: 'Lencse alakú galaxis' },
    { id: 'M103', ngc: 'NGC 581', const: 'Cas', type: 'OC', mag: 7.4, size: '6', name: '', desc: 'Nyílthalmaz' },
    { id: 'M104', ngc: 'NGC 4594', const: 'Vir', type: 'GAL', mag: 8.0, size: '9x4', name: 'Sombrero-galaxis', desc: 'Spirálgalaxis' },
    { id: 'M105', ngc: 'NGC 3379', const: 'Leo', type: 'GAL', mag: 9.3, size: '5x4', name: '', desc: 'Elliptikus galaxis' },
    { id: 'M106', ngc: 'NGC 4258', const: 'CVn', type: 'GAL', mag: 8.4, size: '19x7', name: '', desc: 'Spirálgalaxis' },
    { id: 'M107', ngc: 'NGC 6171', const: 'Oph', type: 'GC', mag: 7.9, size: '13', name: '', desc: 'Gömbhalmaz' },
    { id: 'M108', ngc: 'NGC 3556', const: 'UMa', type: 'GAL', mag: 10.0, size: '9x2', name: '', desc: 'Spirálgalaxis' },
    { id: 'M109', ngc: 'NGC 3992', const: 'UMa', type: 'GAL', mag: 9.8, size: '8x5', name: '', desc: 'Spirálgalaxis' },
    { id: 'M110', ngc: 'NGC 205', const: 'And', type: 'GAL', mag: 8.5, size: '17x10', name: '', desc: 'Elliptikus galaxis' }
];

// Selected Melotte Objects (Top 20)
export const melotte = [
    { id: 'Mel 20', ngc: '-', const: 'Per', type: 'OC', mag: 1.2, size: '185', name: 'Alpha Persei Cluster', desc: 'Nyílthalmaz' },
    { id: 'Mel 25', ngc: '-', const: 'Tau', type: 'OC', mag: 0.5, size: '330', name: 'Hyadok', desc: 'Nyílthalmaz' },
    { id: 'Mel 111', ngc: '-', const: 'Com', type: 'OC', mag: 1.8, size: '275', name: 'Coma Berenices Cluster', desc: 'Nyílthalmaz' },
    { id: 'Mel 15', ngc: 'IC 1805', const: 'Cas', type: 'OC', mag: 6.5, size: '20', name: 'Szív-köd közepe', desc: 'Nyílthalmaz' },
    { id: 'Mel 22', ngc: 'M45', const: 'Tau', type: 'OC', mag: 1.6, size: '110', name: 'Fiastyúk', desc: 'Nyílthalmaz' }
];

// Selected NGC Objects (Top 50 Non-Messier)
export const ngc = [
    { id: 'NGC 869', ngc: 'NGC 869', const: 'Per', type: 'OC', mag: 5.3, size: '30', name: 'Ikerhalmaz (h Per)', desc: 'Nyílthalmaz' },
    { id: 'NGC 884', ngc: 'NGC 884', const: 'Per', type: 'OC', mag: 6.1, size: '30', name: 'Ikerhalmaz (chi Per)', desc: 'Nyílthalmaz' },
    { id: 'NGC 457', ngc: 'NGC 457', const: 'Cas', type: 'OC', mag: 6.4, size: '13', name: 'Bagoly-halmaz', desc: 'Nyílthalmaz' },
    { id: 'NGC 7789', ngc: 'NGC 7789', const: 'Cas', type: 'OC', mag: 6.7, size: '16', name: 'Caroline rózsája', desc: 'Nyílthalmaz' },
    { id: 'NGC 253', ngc: 'NGC 253', const: 'Scl', type: 'GAL', mag: 7.2, size: '28x7', name: 'Szobrász-galaxis', desc: 'Spirálgalaxis' },
    { id: 'NGC 2403', ngc: 'NGC 2403', const: 'Cam', type: 'GAL', mag: 8.4, size: '22x12', name: '', desc: 'Spirálgalaxis' },
    { id: 'NGC 2903', ngc: 'NGC 2903', const: 'Leo', type: 'GAL', mag: 8.9, size: '13x6', name: '', desc: 'Spirálgalaxis' },
    { id: 'NGC 6946', ngc: 'NGC 6946', const: 'Cep', type: 'GAL', mag: 8.8, size: '11x10', name: 'Tűzijáték-galaxis', desc: 'Spirálgalaxis' },
    { id: 'NGC 7331', ngc: 'NGC 7331', const: 'Peg', type: 'GAL', mag: 9.5, size: '10x4', name: '', desc: 'Spirálgalaxis' },
    { id: 'NGC 2392', ngc: 'NGC 2392', const: 'Gem', type: 'PN', mag: 9.1, size: '0.8', name: 'Eszkimó-köd', desc: 'Planetáris köd' },
    { id: 'NGC 6543', ngc: 'NGC 6543', const: 'Dra', type: 'PN', mag: 8.1, size: '0.4', name: 'Macskaszem-köd', desc: 'Planetáris köd' },
    { id: 'NGC 7000', ngc: 'NGC 7000', const: 'Cyg', type: 'NB', mag: 4.0, size: '120x100', name: 'Észak-Amerika köd', desc: 'Emissziós köd' },
    { id: 'NGC 6960', ngc: 'NGC 6960', const: 'Cyg', type: 'SNR', mag: 7.0, size: '70x6', name: 'Fátyol-köd (Nyugat)', desc: 'Szupernóva-maradvány' },
    { id: 'NGC 6992', ngc: 'NGC 6992', const: 'Cyg', type: 'SNR', mag: 7.0, size: '60x8', name: 'Fátyol-köd (Kelet)', desc: 'Szupernóva-maradvány' },
    { id: 'NGC 2244', ngc: 'NGC 2244', const: 'Mon', type: 'OC', mag: 4.8, size: '24', name: 'Rozetta-halmaz', desc: 'Nyílthalmaz' },
    { id: 'NGC 2264', ngc: 'NGC 2264', const: 'Mon', type: 'OC', mag: 3.9, size: '20', name: 'Karácsonyfa-halmaz', desc: 'Nyílthalmaz' },
    { id: 'NGC 5139', ngc: 'NGC 5139', const: 'Cen', type: 'GC', mag: 3.7, size: '36', name: 'Omega Centauri', desc: 'Gömbhalmaz' },
    { id: 'NGC 104', ngc: 'NGC 104', const: 'Tuc', type: 'GC', mag: 4.0, size: '31', name: '47 Tucanae', desc: 'Gömbhalmaz' },
    { id: 'NGC 3372', ngc: 'NGC 3372', const: 'Car', type: 'NB', mag: 1.0, size: '120', name: 'Eta Carinae köd', desc: 'Emissziós köd' },
    { id: 'NGC 4755', ngc: 'NGC 4755', const: 'Cru', type: 'OC', mag: 4.2, size: '10', name: 'Ékszerdoboz', desc: 'Nyílthalmaz' },
    { id: 'NGC 3532', ngc: 'NGC 3532', const: 'Car', type: 'OC', mag: 3.0, size: '50', name: 'Kívánságkút-halmaz', desc: 'Nyílthalmaz' },
    { id: 'NGC 2516', ngc: 'NGC 2516', const: 'Car', type: 'OC', mag: 3.8, size: '30', name: 'Déli Fiastyúk', desc: 'Nyílthalmaz' },
    { id: 'IC 2602', ngc: 'IC 2602', const: 'Car', type: 'OC', mag: 1.9, size: '50', name: 'Déli Fiastyúk (Theta Car)', desc: 'Nyílthalmaz' },
    { id: 'NGC 6231', ngc: 'NGC 6231', const: 'Sco', type: 'OC', mag: 2.6, size: '15', name: 'Déli Ékszerdoboz', desc: 'Nyílthalmaz' },
    { id: 'NGC 7293', ngc: 'NGC 7293', const: 'Aqr', type: 'PN', mag: 7.3, size: '16', name: 'Csiga-köd', desc: 'Planetáris köd' },
    { id: 'NGC 281', ngc: 'NGC 281', const: 'Cas', type: 'NB', mag: 7.0, size: '35x30', name: 'Pacman-köd', desc: 'Emissziós köd' },
    { id: 'NGC 891', ngc: 'NGC 891', const: 'And', type: 'GAL', mag: 9.9, size: '13x3', name: 'Külső-határvidék galaxis', desc: 'Spirálgalaxis' },
    { id: 'NGC 4631', ngc: 'NGC 4631', const: 'CVn', type: 'GAL', mag: 9.2, size: '15x3', name: 'Bálna-galaxis', desc: 'Spirálgalaxis' },
    { id: 'NGC 4565', ngc: 'NGC 4565', const: 'Com', type: 'GAL', mag: 9.6, size: '16x3', name: 'Tű-galaxis', desc: 'Spirálgalaxis' },
    { id: 'NGC 6888', ngc: 'NGC 6888', const: 'Cyg', type: 'NB', mag: 10.0, size: '18x13', name: 'Sarló-köd', desc: 'Emissziós köd' },
    { id: 'NGC 7662', ngc: 'NGC 7662', const: 'And', type: 'PN', mag: 8.3, size: '0.5', name: 'Kék Hógolyó', desc: 'Planetáris köd' },
    { id: 'NGC 3242', ngc: 'NGC 3242', const: 'Hya', type: 'PN', mag: 7.7, size: '0.7', name: 'Jupiter szelleme', desc: 'Planetáris köd' }
];

export const catalogs = [...messier, ...melotte, ...ngc];

export const constellations = {
    'And': 'Andromeda', 'Ant': 'Antlia', 'Aps': 'Apus', 'Aql': 'Aquila', 'Aqr': 'Aquarius', 'Ara': 'Ara',
    'Ari': 'Aries', 'Aur': 'Auriga', 'Boo': 'Boötes', 'Cae': 'Caelum', 'Cam': 'Camelopardalis', 'Cnc': 'Cancer',
    'CVn': 'Canes Venatici', 'CMa': 'Canis Major', 'CMi': 'Canis Minor', 'Cap': 'Capricornus', 'Car': 'Carina',
    'Cas': 'Cassiopeia', 'Cen': 'Centaurus', 'Cep': 'Cepheus', 'Cet': 'Cetus', 'Cha': 'Chamaeleon', 'Cir': 'Circinus',
    'Col': 'Columba', 'Com': 'Coma Berenices', 'CrA': 'Corona Australis', 'CrB': 'Corona Borealis', 'Crv': 'Corvus',
    'Crt': 'Crater', 'Cru': 'Crux', 'Cyg': 'Cygnus', 'Del': 'Delphinus', 'Dor': 'Dorado', 'Dra': 'Draco',
    'Equ': 'Equuleus', 'Eri': 'Eridanus', 'For': 'Fornax', 'Gem': 'Gemini', 'Gru': 'Grus', 'Her': 'Hercules',
    'Hor': 'Horologium', 'Hya': 'Hydra', 'Hyi': 'Hydrus', 'Ind': 'Indus', 'Lac': 'Lacerta', 'Leo': 'Leo',
    'LMi': 'Leo Minor', 'Lep': 'Lepus', 'Lib': 'Libra', 'Lup': 'Lupus', 'Lyn': 'Lynx', 'Lyr': 'Lyra',
    'Men': 'Mensa', 'Mic': 'Microscopium', 'Mon': 'Monoceros', 'Mus': 'Musca', 'Nor': 'Norma', 'Oct': 'Octans',
    'Oph': 'Ophiuchus', 'Ori': 'Orion', 'Pav': 'Pavo', 'Peg': 'Pegasus', 'Per': 'Perseus', 'Phe': 'Phoenix',
    'Pic': 'Pictor', 'Psc': 'Pisces', 'PsA': 'Piscis Austrinus', 'Pup': 'Puppis', 'Pyx': 'Pyxis', 'Ret': 'Reticulum',
    'Sge': 'Sagitta', 'Sgr': 'Sagittarius', 'Sco': 'Scorpius', 'Scl': 'Sculptor', 'Sct': 'Scutum', 'Ser': 'Serpens',
    'Sex': 'Sextans', 'Tau': 'Taurus', 'Tel': 'Telescopium', 'Tri': 'Triangulum', 'TrA': 'Triangulum Australe',
    'Tuc': 'Tucana', 'UMa': 'Ursa Major', 'UMi': 'Ursa Minor', 'Vel': 'Vela', 'Vir': 'Virgo', 'Vol': 'Volans', 'Vul': 'Vulpecula'
};

export const objectTypes = {
    'GAL': 'Galaxis',
    'PN': 'Planetáris köd',
    'NB': 'Köd',
    'OC': 'Nyílthalmaz',
    'GC': 'Gömbhalmaz',
    'SNR': 'Szupernóva-maradvány',
    'DS': 'Kettőscsillag',
    'STAR': 'Csillag'
};
